export * from "./proveedor.interface";
export * from "./partidaPresupuestal.interface";
export * from "./requisicion.interface";
export * from "./ordenCompra.interface";
export * from "./ordenPago.interface";
export * from "./solicitud.interface";
export * from "./presupuestoAnual.interface";
export * from "./usuario.interface";
export * from "./auth-request";
